[package]
name = "aura_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
teloxide = { version = "0.13", features = ["macros"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
aura_api_client = { git = "https://github.com/in-aura-we-trade/aura_api_client" }
governor = "0.6.0"
nonzero_ext = "0.3.0"
log = "0.4"
pretty_env_logger = "0.5"
