[package]
name = "aura_bot"
version = "0.1.0"
edition = "2021"
default-run = "aura_bot"

[dependencies]
teloxide = { version = "0.12", features = ["macros", "rustls"] }
tokio = { version = "1.8", features = ["rt-multi-thread", "macros"] }
log = "0.4"
pretty_env_logger = "0.5"
governor = "0.6"
nonzero_ext = "0.3"
aura_api_client = { git = "https://github.com/in-aura-we-trade/aura_api_client.git", features = ["client", "client-generic", "api-types"], version = "0.1.0" }
tonic = "0.14"
tokio-stream = "0.1"
prost = "0.13"
dotenvy = "0.15.7"
fastnum = "0.7.4"
decisol = { git = "https://github.com/4r33x/decisol", version = "1.0.1" }
solana-address = "2.7.0"
rusqlite = { version = "0.40.2", features = ["bundled"] }
reqwest = { version = "0.12", features = ["json", "rustls-tls"], default-features = false }
serde_json = "1"
